# Generated by Django 3.0.4 on 2020-03-15 22:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.PositiveIntegerField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.PositiveIntegerField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(default=None, upload_to='characters/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfficeApp.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.PositiveIntegerField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField()),
                ('air_date', models.DateTimeField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.PositiveIntegerField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.PositiveIntegerField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by', models.PositiveIntegerField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=999)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfficeApp.Character')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfficeApp.Episode')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OfficeApp.Season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='directed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='OfficeApp.StaffMember'),
        ),
        migrations.AddField(
            model_name='episode',
            name='written_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='OfficeApp.StaffMember'),
        ),
    ]
