# Generated by Django 3.0.4 on 2020-03-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0002_auto_20200315_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='modified_by',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='actor',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='modified_by',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='character',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='episode',
            name='directed_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='episodes_d', to='OfficeApp.StaffMember'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='modified_by',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='episode',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='episode',
            name='written_by',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='episodes_w', to='OfficeApp.StaffMember'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='modified_by',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='quote',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='season',
            name='modified_by',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='season',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='modified_by',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='modified_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
