# Generated by Django 3.0.4 on 2020-03-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0006_auto_20200315_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='written_by',
        ),
    ]
