# Generated by Django 3.0.4 on 2020-03-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0008_episode_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
