# Generated by Django 3.0.4 on 2020-03-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0010_episode_running_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='season',
        ),
    ]
