# Generated by Django 3.0.4 on 2020-03-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0011_remove_quote_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='created_by',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_by',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_by',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='season',
            name='created_by',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='created_by',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
