# Generated by Django 3.0.4 on 2020-03-16 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApp', '0012_auto_20200316_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='title',
        ),
    ]
